"""update rivals join table

Revision ID: a46f6b45c561
Revises: 4fd21fc91b58
Create Date: 2020-12-28 18:59:24.878244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46f6b45c561'
down_revision = '4fd21fc91b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rivals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rival_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rival_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'rival_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rivals')
    # ### end Alembic commands ###
