"""create tables

Revision ID: 21023b356969
Revises: eb265ba63538
Create Date: 2020-12-28 17:12:52.125995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21023b356969'
down_revision = 'eb265ba63538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'routes', 'users', ['user_creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    # ### end Alembic commands ###
